name: SSO UI Renew Notice

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 8 * * *"

jobs:
  sso_ui_renew_notice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '77.0.3865.40'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sso login script
        env:
          SSO_USERNAME: ${{ secrets.SSO_USERNAME }}
          SSO_PASSWORD: ${{ secrets.SSO_PASSWORD }}
        run: |
          python sso-login.py > renew-notice.out
          echo  " :: set-env name = MESSAGE :: $ ( cat renew-notice.out ) "

      #      - name: Commit changes
      #        run: |
      #          git config --local user.email "argaghulamahmad@gmail.com"
      #          git config --local user.name "Arga Ghulam Ahmad"
      #          git add -A
      #
      #          git commit -m "SSO UI Renew Notice"
      #
      #      - name: GitHub Push
      #        uses: ad-m/github-push-action@v0.5.0
      #        with:
      #          force: true
      #          directory: "."
      #          github_token: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Send mail
      #        uses: dawidd6/action-send-mail@v2
      #        with:
      #          server_address: smtp.gmail.com
      #          server_port: 465
      #          username: ${{secrets.MAIL_USERNAME}}
      #          password: ${{secrets.MAIL_PASSWORD}}
      #          subject: SSO UI Renew Notice
      #          # Read file contents as body:
      #          body: file://renew-notice.out
      #          to: argaghulamahmad@gmail.com
      #          from: SSO UI Renew Notice
      #          # Optional content type (defaults to text/plain):
      #          content_type: text/html

      - name: Send Push Notification
        uses: techulus/push-github-action@v0.0.2
        env:
          API_KEY: ${{ secrets.PUSH_NOTIFICATION_API_KEY }}

      - name: Delete renew-notice out file
        run: |
          rm -rf renew-notice.out
